-- FinansApp — Initial Migration
-- Generated by Prisma Migrate

-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE "PaymentStatus"   AS ENUM ('PENDING', 'PAID', 'OVERDUE', 'CANCELLED');
CREATE TYPE "Category"        AS ENUM ('SALARY','RENT','GROCERIES','UTILITIES','FUEL','CREDIT_CARD','EDUCATION','HEALTHCARE','ENTERTAINMENT','INVESTMENT','TRANSFER','OTHER');
CREATE TYPE "BudgetPeriod"    AS ENUM ('MONTHLY', 'YEARLY');
CREATE TYPE "CardNetwork"     AS ENUM ('VISA','MASTERCARD','AMEX','TROY','OTHER');
CREATE TYPE "Role"            AS ENUM ('USER', 'ADMIN');

-- Users
CREATE TABLE "users" (
    "id"            TEXT        NOT NULL,
    "name"          TEXT,
    "email"         TEXT        NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "image"         TEXT,
    "password"      TEXT,
    "role"          "Role"      NOT NULL DEFAULT 'USER',
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "users_email_idx" ON "users"("email");

-- Accounts (OAuth)
CREATE TABLE "accounts" (
    "id"                TEXT NOT NULL,
    "userId"            TEXT NOT NULL,
    "type"              TEXT NOT NULL,
    "provider"          TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token"     TEXT,
    "access_token"      TEXT,
    "expires_at"        INTEGER,
    "token_type"        TEXT,
    "scope"             TEXT,
    "id_token"          TEXT,
    "session_state"     TEXT,
    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "accounts_provider_providerAccountId_key" ON "accounts"("provider","providerAccountId");
CREATE INDEX "accounts_userId_idx" ON "accounts"("userId");

-- Sessions
CREATE TABLE "sessions" (
    "id"           TEXT         NOT NULL,
    "sessionToken" TEXT         NOT NULL,
    "userId"       TEXT         NOT NULL,
    "expires"      TIMESTAMP(3) NOT NULL,
    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "sessions_sessionToken_key" ON "sessions"("sessionToken");
CREATE INDEX "sessions_userId_idx" ON "sessions"("userId");

-- Verification tokens
CREATE TABLE "verification_tokens" (
    "identifier" TEXT         NOT NULL,
    "token"      TEXT         NOT NULL,
    "expires"    TIMESTAMP(3) NOT NULL
);
CREATE UNIQUE INDEX "verification_tokens_token_key" ON "verification_tokens"("token");
CREATE UNIQUE INDEX "verification_tokens_identifier_token_key" ON "verification_tokens"("identifier","token");

-- Password reset tokens
CREATE TABLE "password_reset_tokens" (
    "id"        TEXT         NOT NULL,
    "email"     TEXT         NOT NULL,
    "token"     TEXT         NOT NULL,
    "expires"   TIMESTAMP(3) NOT NULL,
    "used"      BOOLEAN      NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "password_reset_tokens_token_key" ON "password_reset_tokens"("token");
CREATE INDEX "password_reset_tokens_email_idx" ON "password_reset_tokens"("email");
CREATE INDEX "password_reset_tokens_token_idx" ON "password_reset_tokens"("token");

-- User settings
CREATE TABLE "user_settings" (
    "id"                 TEXT         NOT NULL,
    "userId"             TEXT         NOT NULL,
    "currency"           TEXT         NOT NULL DEFAULT 'TRY',
    "locale"             TEXT         NOT NULL DEFAULT 'tr-TR',
    "darkMode"           BOOLEAN      NOT NULL DEFAULT false,
    "emailNotifications" BOOLEAN      NOT NULL DEFAULT true,
    "reminderDaysBefore" INTEGER      NOT NULL DEFAULT 3,
    "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"          TIMESTAMP(3) NOT NULL,
    CONSTRAINT "user_settings_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "user_settings_userId_key" ON "user_settings"("userId");

-- Transactions
CREATE TABLE "transactions" (
    "id"           TEXT              NOT NULL,
    "userId"       TEXT              NOT NULL,
    "date"         DATE              NOT NULL,
    "description"  VARCHAR(200)      NOT NULL,
    "category"     "Category"        NOT NULL,
    "amount"       DECIMAL(14,2)     NOT NULL,
    "type"         "TransactionType" NOT NULL,
    "notes"        VARCHAR(500),
    "creditCardId" TEXT,
    "createdAt"    TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"    TIMESTAMP(3)      NOT NULL,
    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "transactions_userId_date_idx"      ON "transactions"("userId","date");
CREATE INDEX "transactions_userId_type_idx"      ON "transactions"("userId","type");
CREATE INDEX "transactions_userId_category_idx"  ON "transactions"("userId","category");
CREATE INDEX "transactions_userId_date_type_idx" ON "transactions"("userId","date","type");
CREATE INDEX "transactions_creditCardId_idx"     ON "transactions"("creditCardId");

-- Payments
CREATE TABLE "payments" (
    "id"              TEXT            NOT NULL,
    "userId"          TEXT            NOT NULL,
    "name"            VARCHAR(100)    NOT NULL,
    "description"     VARCHAR(300),
    "amount"          DECIMAL(14,2)   NOT NULL,
    "dueDate"         DATE            NOT NULL,
    "startDate"       DATE            NOT NULL,
    "endDate"         DATE,
    "category"        "Category"      NOT NULL,
    "status"          "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "completed"       BOOLEAN         NOT NULL DEFAULT false,
    "completedAt"     TIMESTAMP(3),
    "reminderSentAt"  TIMESTAMP(3),
    "notes"           VARCHAR(500),
    "createdAt"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"       TIMESTAMP(3)    NOT NULL,
    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "payments_userId_status_idx"         ON "payments"("userId","status");
CREATE INDEX "payments_userId_dueDate_idx"        ON "payments"("userId","dueDate");
CREATE INDEX "payments_userId_completed_due_idx"  ON "payments"("userId","completed","dueDate");

-- Credit cards
CREATE TABLE "credit_cards" (
    "id"              TEXT          NOT NULL,
    "userId"          TEXT          NOT NULL,
    "name"            VARCHAR(100)  NOT NULL,
    "lastFourDigits"  CHAR(4)       NOT NULL,
    "network"         "CardNetwork" NOT NULL DEFAULT 'VISA',
    "creditLimit"     DECIMAL(14,2) NOT NULL,
    "currentBalance"  DECIMAL(14,2) NOT NULL DEFAULT 0,
    "statementDate"   INTEGER       NOT NULL,
    "dueDate"         INTEGER       NOT NULL,
    "color"           TEXT          NOT NULL DEFAULT '#6366f1',
    "isActive"        BOOLEAN       NOT NULL DEFAULT true,
    "createdAt"       TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"       TIMESTAMP(3)  NOT NULL,
    CONSTRAINT "credit_cards_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "credit_cards_userId_idx"        ON "credit_cards"("userId");
CREATE INDEX "credit_cards_userId_active_idx" ON "credit_cards"("userId","isActive");

-- Card statements
CREATE TABLE "card_statements" (
    "id"              TEXT          NOT NULL,
    "creditCardId"    TEXT          NOT NULL,
    "periodStart"     DATE          NOT NULL,
    "periodEnd"       DATE          NOT NULL,
    "statementAmount" DECIMAL(14,2) NOT NULL,
    "minimumPayment"  DECIMAL(14,2) NOT NULL,
    "dueDate"         DATE          NOT NULL,
    "isPaid"          BOOLEAN       NOT NULL DEFAULT false,
    "paidAt"          TIMESTAMP(3),
    "createdAt"       TIMESTAMP(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"       TIMESTAMP(3)  NOT NULL,
    CONSTRAINT "card_statements_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "card_statements_creditCardId_idx"            ON "card_statements"("creditCardId");
CREATE INDEX "card_statements_creditCardId_period_idx"     ON "card_statements"("creditCardId","periodStart");

-- Budgets
CREATE TABLE "budgets" (
    "id"        TEXT           NOT NULL,
    "userId"    TEXT           NOT NULL,
    "name"      VARCHAR(100)   NOT NULL,
    "category"  "Category"     NOT NULL,
    "amount"    DECIMAL(14,2)  NOT NULL,
    "period"    "BudgetPeriod" NOT NULL DEFAULT 'MONTHLY',
    "year"      INTEGER        NOT NULL,
    "month"     INTEGER,
    "alertAt"   INTEGER        NOT NULL DEFAULT 80,
    "color"     TEXT           NOT NULL DEFAULT '#6366f1',
    "createdAt" TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3)   NOT NULL,
    CONSTRAINT "budgets_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "budgets_userId_category_year_month_key" ON "budgets"("userId","category","year","month");
CREATE INDEX "budgets_userId_year_month_idx" ON "budgets"("userId","year","month");

-- Audit log
CREATE TABLE "audit_logs" (
    "id"         TEXT         NOT NULL,
    "userId"     TEXT         NOT NULL,
    "action"     TEXT         NOT NULL,
    "entityType" TEXT         NOT NULL,
    "entityId"   TEXT         NOT NULL,
    "metadata"   JSONB,
    "ipAddress"  VARCHAR(45),
    "userAgent"  VARCHAR(500),
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "audit_logs_userId_createdAt_idx"  ON "audit_logs"("userId","createdAt");
CREATE INDEX "audit_logs_entityType_id_idx"     ON "audit_logs"("entityType","entityId");

-- Foreign keys
ALTER TABLE "accounts"          ADD CONSTRAINT "accounts_userId_fkey"          FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "sessions"          ADD CONSTRAINT "sessions_userId_fkey"          FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "user_settings"     ADD CONSTRAINT "user_settings_userId_fkey"     FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "transactions"      ADD CONSTRAINT "transactions_userId_fkey"      FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "transactions"      ADD CONSTRAINT "transactions_creditCardId_fkey" FOREIGN KEY ("creditCardId") REFERENCES "credit_cards"("id") ON DELETE SET NULL;
ALTER TABLE "payments"          ADD CONSTRAINT "payments_userId_fkey"          FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "credit_cards"      ADD CONSTRAINT "credit_cards_userId_fkey"      FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
ALTER TABLE "card_statements"   ADD CONSTRAINT "card_statements_cardId_fkey"   FOREIGN KEY ("creditCardId") REFERENCES "credit_cards"("id") ON DELETE CASCADE;
ALTER TABLE "budgets"           ADD CONSTRAINT "budgets_userId_fkey"           FOREIGN KEY ("userId")       REFERENCES "users"("id")        ON DELETE CASCADE;
